export const locations = ["delhi", "mumbai"];

export const flightss = [
  {
    name: "Jet Airways",
    number: "Flight 3",
    from: "delhi",
    to: "mumbai",
    date: new Date("2023-10-20"),
    price: "6500",
  },
  {
    name: "SpiceJet",
    number: "Flight 4",
    from: "delhi",
    to: "mumbai",
    date: new Date("2023-10-21"),
    price: "5500",
  },
  {
    name: "Vistara",
    number: "Flight 5",
    from: "delhi",
    to: "mumbai",
    date: new Date("2023-10-22"),
    price: "6200",
  },
  {
    name: "GoAir",
    number: "Flight 6",
    from: "delhi",
    to: "mumbai",
    date: new Date("2023-10-23"),
    price: "5300",
  },
  {
    name: "Air Asia",
    number: "Flight 7",
    from: "delhi",
    to: "mumbai",
    date: new Date("2023-10-24"),
    price: "5800",
  },
  {
    name: "SpiceJet",
    number: "Flight 8",
    from: "delhi",
    to: "mumbai",
    date: new Date("2023-10-25"),
    price: "5400",
  },
  {
    name: "IndiGo",
    number: "Flight 9",
    from: "delhi",
    to: "mumbai",
    date: new Date("2023-10-26"),
    price: "6100",
  },
  {
    name: "Air India",
    number: "Flight 10",
    from: "delhi",
    to: "mumbai",
    date: new Date("2023-10-27"),
    price: "4900",
  },
  {
    name: "Vistara",
    number: "Flight 12",
    from: "delhi",
    to: "mumbai",
    date: new Date("2023-10-29"),
    price: "6250",
  },
  {
    name: "Air Asia",
    number: "Flight 13",
    from: "delhi",
    to: "mumbai",
    date: new Date("2023-10-30"),
    price: "5900",
  },
  {
    name: "Jet Airways",
    number: "Flight 14",
    from: "delhi",
    to: "mumbai",
    date: new Date("2023-10-31"),
    price: "6550",
  },
  {
    name: "SpiceJet",
    number: "Flight 15",
    from: "delhi",
    to: "mumbai",
    date: new Date("2023-11-01"),
    price: "5450",
  },
  {
    name: "IndiGo",
    number: "Flight 16",
    from: "delhi",
    to: "mumbai",
    date: new Date("2023-11-02"),
    price: "6150",
  },
  {
    name: "GoAir",
    number: "Flight 17",
    from: "delhi",
    to: "mumbai",
    date: new Date("2023-11-03"),
    price: "5300",
  },
  {
    name: "Vistara",
    number: "Flight 18",
    from: "delhi",
    to: "mumbai",
    date: new Date("2023-11-04"),
    price: "6300",
  },
  {
    name: "Air India",
    number: "Flight 19",
    from: "delhi",
    to: "mumbai",
    date: new Date("2023-11-05"),
    price: "4850",
  },
  {
    name: "Air Asia",
    number: "Flight 20",
    from: "delhi",
    to: "mumbai",
    date: new Date("2023-11-06"),
    price: "5850",
  },
  {
    name: "Jet Airways",
    number: "Flight 21",
    from: "delhi",
    to: "mumbai",
    date: new Date("2023-11-07"),
    price: "6600",
  },
  {
    name: "IndiGo",
    number: "Flight 22",
    from: "delhi",
    to: "mumbai",
    date: new Date("2023-11-08"),
    price: "6100",
  },
];
